JSON View
Resource group (move)
:
Project-Resume-RG
Location
:
southafricanorth
Subscription (move)
:
Azure for Students
Subscription ID
:
5e01d446-c230-4dc6-aee5-f0218e2321dc
Disk state
:
Available
Performance
:
Standard
Replication
:
Locally-redundant storage (LRS)
Account kind
:
StorageV2 (general purpose v2)
Provisioning state
:
Succeeded
Created
:
2/26/2026, 4:52:20 PM
Tags (edit)
:
Add tags
